name: Lint, Test & Deploy on Container runner
on:
  workflow_dispatch:
permissions:
  checks: write
  contents: write
  issues: write
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install dependecies
        run: |
          npm ci
      - name: Lint
        run: |
          npm run lint
      - name: Test
        run: |
          npm test
      - name: Deploy
        run: |
          echo "Deploying..."
      - name: Create issue
        run: |
#          gh issue create --title "Issue report" --body "something happened." --repo $GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
